export enum ColorFamily {
  BLACK = 'black',
  WHITE = 'white',
  RED = 'red',
  BLUE = 'blue',
  GREEN = 'green',
  YELLOW = 'yellow',
  ORANGE = 'orange',
  PINK = 'pink',
  PURPLE = 'purple',
  GREY = 'grey',
  SILVER = 'silver',
  GOLD = 'gold',
  BROWN = 'brown',
  CARBON = 'carbon',
  MULTICOLOR = 'multicolor',
  BRONZE = 'bronze',
  HI_VIS = 'hi_vis',
  IRIDISCENT = 'iridescent',
}
